mosplex::
	cl /W4 mosplex.c
	./mosplex.exe in/mosplex.in > out/mosplex.out
	./mosplex.exe in/mosplex-cormen29-3.in > out/mosplex-cormen29-3.out
	./mosplex.exe in/mosplex-rorres19-5.in > out/mosplex-rorres19-5.out
	#dos2unix x

clean::
	rm -fv *.pyc *.obj *.exe x
