java::
	c:/java/jdk16/bin/javac.exe karatsuba.java
	c:/java/jdk16/bin/java.exe -cp . Karatsuba 10

c:
	cl /W4 karatsuba.c
	./karatsuba.exe

py::
	./karatsuba.py

horner::
	cl /W4 horner.c
	./horner.exe

clean::
	rm -fv *.class *.obj *.exe
