# Jokes
print('What do you get when you cross a snowman with a vampire?')
input()
print('Frostbite!')
print()
print('What do dentists call an astronaut\'s cavity?')
input()
print('A black hol!')
print()
print('Knock knock.')
print("Who's there?")
print('Interrupting cow.')
input()
print('Intrrupting cow wh', end='')
print('-MOO!')
