/*─────────────────────────────────────────────────────── checkParen.c
 │ Program : checkParen(const char* filename)
 │ Author  : william h robertson
 │
 │ Purpose : check album file albums has matching {} on artist's name
 │           when needed & that the albums all have bit rate in ()
 │
 │ Params  : Filename of the album file to check
 │
 │ Returns : Number of errors to system & prints lines with errors to
 │           stdout.
 │
 │ Usage   : checkParen gMusic.txt <--an album file generated by
 │                                    music2 g:\Music, for example)
 │ Requires: An album file generated by music2.exe
 │
 │ Notes   : gcc -o checkParen checkParen.c -L\src\lib -lwhr
 │
 │   Ver       Date         Who     Description of the Change
 │     1    07-20-2016      whr     Initial release
 │
 └────────────────────────────────────────────────────────────────────
 */
#include <stdio.h>
#include <strings.h>
#include <stdlib.h>

#define MAX_LINE  120
#define DEFAULT_FILE  "gMusic.txt"

int   SpacesBefore(char *str);           // In libwhr.a
int   chkBraces(char *line, char *brace, int nAlbums);
char *rtrim(char *string);
char *version = "Rev 01  2017-07-20";
char  buffer[12];

int
main(int argc, char * argv[])
{
   FILE *in;
   char line[MAX_LINE];
   int  nLen = 0;
   int  nArtist = 0;
   int  nAlbums = 0;
   int  nLines  = 0;
   int  nErrors = 0;
   int  nSpaces = 0;

   if(argc == 2){
      if((in = fopen(argv[1], "r")) == NULL){
         printf("Error opening %s\n", argv[1]);
         return 1;
      }
   }
   else{
      if((in = fopen(DEFAULT_FILE, "r")) == NULL){
         printf("Error opening %s\n", DEFAULT_FILE);
         return 1;
      }
   }

   fprintf(stdout, "\n%s  %s\n  Input file: %s\n",
                   argv[0], version, argv[1]);

   while(fgets(line, MAX_LINE, in) != NULL)
   {
      ++nLines;
      // Check Albums for bit-rate i.e. ()
      if((nSpaces = SpacesBefore(line)) == 4){
         ++nAlbums;
         nErrors += chkBraces(line, "()", nLines);
      }

      // Check Artists for {}, may not be present
      if(nSpaces == 2){
         ++nArtist;
         
      }
   }

   // min space needed to print results using %*d format
   nLen = strlen(itoa(nAlbums, buffer, 10));
   fprintf(stdout, "\nNumber errors : %*d\n", nLen, nErrors);
   fprintf(stdout,   "Number artists: %*d\n", nLen, nArtist);
   fprintf(stdout,   "Number albums : %*d\n", nLen, nAlbums);
   fclose(in);

   return 0;
}

/*──────────────────────────────────────────────────────── chkBraces()
 │ Function: chkBraces(char *line, char *brace, nAlbums)
 │
 │ Purpose : Check for opening and closing braces, brackets, etc.
 │
 │ Params  : line     The null terminated line to check
 │           char     2-char string with left & right chars to check
 │           nAlbums  About where the album is in the file
 │
 │ Returns : 0 if no error or 1 if error
 └────────────────────────────────────────────────────────────────────
 */
int
chkBraces(char *line, char *brace,int  nAlbums){
   int    nError = 0;
   size_t nLen   = 0;

   char lBrace = brace[0];
   char rBrace = brace[1];

   // remove trailing spaces
   if(rtrim(line) == NULL){
      fprintf(stderr, "NULL for line %d in chkParen\n", nAlbums);
      exit(EXIT_FAILURE);
   }
   nLen = strlen(line);
   if((char) line[nLen-1] != rBrace){
      fprintf(stdout, "  Line#: %5d %s\n", nAlbums, line);
      return ++nError;       // No need to check for lBrace
   }

   if(strchr(line, lBrace) == NULL){
      // Didn't find left brace
      fprintf(stdout, "  Line#: %5d %s\n", nAlbums, line);
      return ++nError;
   }

   return nError;
}
